blog/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
    re_path(r'^(?P<pk>\d+)/$', views.EntryDetail.as_view(), name='entry_detail'),
]

tdd2/urls.py
from django.contrib import admin

from django.urls import re_path, include, path

# from django.conf.urls.static import static - Don't need to import static

import blog.urls

from . import views

urlpatterns = [
    # re_path(route, view, kwargs=None, name=None)
    re_path(r'^admin/', admin.site.urls), # pass admin.stie.urls directly. No need include
    re_path(r'^$', views.HomeView.as_view(), name='home'), # Use regex and re_path
    re_path(r'^', include(blog.urls))
    
    # re_path uses regex, path use just <slug:title>.

    # path('admin/', admin.site.urls), # pass admin.stie.urls directly. No need include
    # path('', views.HomeView.as_view(), name='home'), # Use regex
]

blog/models.py
from pyexpat import model
from tabnanny import verbose
from django.db import models
from django.urls import reverse # import reversing has changed to django.urls

# Create your models here.


class Entry(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey('auth.User', on_delete=models.DO_NOTHING)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    modified_at = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        # change the  __self__ method!! from object to title
        return self.title

    def get_absolute_url(self) :
        # by using reverse, get url of entry_detail defined in urls.py 
        # kwargs == arguments are treated as dictionary / args == arguments are treated as tuple type
        return reverse('entry_detail', kwargs={'pk': self.pk})

    class Meta:
        # this will be tested under the _meta class in test.py
        verbose_name_plural = "entries"

class Comment(models.Model) :
    entry = models.ForeignKey(Entry, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    modified_at = models.DateTimeField(auto_now=True, editable=False)

    
    def __str__(self) :
        return self.body

blog/views.py
from django.views.generic.detail import DetailView

from .models import Entry

# show the details of Entry and render it to a template.
class EntryDetail(DetailView) :
    model = Entry

tdd2/views.py
# index view. Not blog application view.

from django.views.generic import ListView

from blog.models import Entry

# TemplateView needs to be ListView 
# from django.views.generic.base import TemplateView


class HomeView(ListView):
    template_name = 'index.html'
    queryset = Entry.objects.order_by('-created_at')

templates/_entry.html
<article>
    <h2><a href="{{ entry.get_absolute_url }}">{{ entry.title }}</a></h2>

    <p class="subheader">
        <time>{{ entry.modified_at|date }}</time>
    </p>
    <p></p>
    {{ entry.body|linebreaks }}
</article>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog</title>
    <link rel="stylesheet" href="{% static 'css/foundation.css' %}">
</head>

<body>
    <section class="row">
        <header class="large-12 columns">
            <h1>Welcome to My Blog</h1>
            <hr>
        </header>
    </section>

    <section class="row">

        <div class="large-8 columns">
            {% block content %} {% endblock %}
        </div>

        <div class="large-4 columns">
            <h3>Abouto Me</h3>
            <p>I am a python developer and I like Django.</p>
            <p>Test-Driven-Dvelopment!</p>
        </div>

    </section>
</body>

</html>

templates/blog/entry_detail.html
{% extends "base.html" %}

{% block content %}
{% include "_entry.html" with entry=entry only %}
<hr>
<h4>Comments</h4>
{% for comment in entry.comment_set.all %}
<p><em>Posted by {{ comment.name }}</em></p>
{{ comment|linebreaks }}
{% empty %}
<p>No comments yet.</p>
{% endfor %}
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}

{% for entry in entry_list %}

{% include "_entry.html" with entry=entry only %}

{% empty %}

<p> No blog entries yet.</p>

{% endfor %}

{% endblock content %}